config/routes.rb
Depot::Application.routes.draw do
  resources :line_items do
    put 'decrease', on: :member
    put 'remove', on: :member
  end

  resources :carts

  get "store/index"

  resources :products

  root :to => 'store#index', :as => 'store'

end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  ORDER_FIELDS = ['price', 'author', 'title']

  def index
    if session[:counter].nil?
      session[:counter] = 1
    else
      session[:counter] += 1
    end

    @count = session[:counter] if session[:counter] > 5
    if(ORDER_FIELDS.include? params[:order_by])
      @products = Product.reorder(  params[:order_by] + " " + (params[:order] == 'asc' ? "ASC" : "DESC")).all
    else
      @products = Product.all
    end
    @cart = current_cart
  end
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/store/_product_cart_buttons.html.erb
<% if(line_item = cart.line_items.find_by_product_id(product_id)) %>
    (<%= line_item.quantity %> item, <%= number_to_currency line_item.total_price %>)
    <%= button_to 'Remove 1', decrease_line_item_path(line_item), :method => :put, :remote => true %>
    <%= button_to 'Remove all', remove_line_item_path(line_item), :method => :put, :remote => true %>
<% end %>

app/views/store/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h1>Your Pragmatic Catalog<%= ' (viewed by you ' + pluralize(@count, 'time') + ')' if  !@count.nil? && @count > 5 %></h1>

<h3>
  Sort by:
  <%= link_to "Price ASC", store_path(:order_by => 'price',:order => 'asc') %> ,
  <%= link_to "Price DESC", store_path(:order_by => 'price') %> ,
  <%= link_to "Author ASC", store_path(:order_by => 'author',:order => 'asc') %> ,
  <%= link_to "Author DESC", store_path(:order_by => 'author') %> ,
  <%= link_to "Title ASC", store_path(:order_by => 'title',:order => 'asc') %> ,
  <%= link_to "Title DESC", store_path(:order_by => 'title') %>

</h3>

<% @products.each do |product| %>
  <div class="entry">
    <%= form_tag line_items_path(:product_id => product), :remote => true do %>
        <%= image_submit_tag product.photo.url(:thumb), :class => 'product_picture'  %>
    <% end %>
    <h3><%= product.title %></h3>
    <%= sanitize(product.description) %>
    <div class="price_line">
      <span class="price"><%= number_to_currency(product.price) %></span>
      <%= button_to 'Add to Cart', line_items_path(:product_id => product),
        :remote => true %>
      <span id="product_cart_buttons<%= product.id %>">
            <%= render :partial => 'product_cart_buttons', :locals => { :cart => @cart, :product_id => product.id } %>
      </span>
    </div>
  </div>
<% end %>